Repository project-studying-dotnet/Streetcode-Server-June, pull requests merged in 2024-07, with the labels that each got.

#225 Enums used for roles. Consider using Normalized names
  Streetcode/Streetcode.DAL/Enums/UserRole.cs
  Streetcode/Streetcode.WebApi/Extensions/SeedingLocalExtension.cs
  Streetcode/Streetcode.WebApi/Program.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/Partners/DeletePartnerHandlerTests.cs
Labels: feature

#223 182 login endpoint and handler
  Streetcode/Streetcode.BLL/DTO/Users/LoginResultDTO.cs
  Streetcode/Streetcode.BLL/DTO/Users/RefreshTokenDTO.cs
  Streetcode/Streetcode.BLL/DTO/Users/TokenResponseDTO.cs
  Streetcode/Streetcode.BLL/DTO/Users/UserDTO.cs
  Streetcode/Streetcode.BLL/DTO/Users/UserLoginDTO.cs
  Streetcode/Streetcode.BLL/DTO/Users/UserRegisterDTO.cs
  Streetcode/Streetcode.BLL/Mapping/Users/UserProfile.cs
  Streetcode/Streetcode.BLL/MediatR/Account/Login/LoginUserCommand.cs
  Streetcode/Streetcode.BLL/MediatR/Account/Login/LoginUserHandler.cs
  Streetcode/Streetcode.BLL/MediatR/Account/Login/LoginUserRequestDTOValidator.cs
  Streetcode/Streetcode.BLL/Resources/ErrorMessages.Designer.cs
  Streetcode/Streetcode.BLL/Resources/ErrorMessages.resx
  Streetcode/Streetcode.BLL/Services/Tokens/TokenService.cs
  Streetcode/Streetcode.WebApi/Controllers/Account/AccountController.cs
  Streetcode/Streetcode.WebApi/Extensions/SeedingLocalExtension.cs
  Streetcode/Streetcode.WebApi/Extensions/ServiceCollectionExtensions.cs
  Streetcode/Streetcode.WebApi/Program.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/Account/Login/LoginUserHandlerTests.cs
Labels: feature

#257 bug with valid rules difference fixed
  Streetcode/Streetcode.BLL/MediatR/Account/Register/RegisterUserRequestDTOValidator.cs
Labels: bug

#273 set cron weekly every monday at 3 am
  Streetcode/Streetcode.WebApi/Program.cs
Labels: feature

#270 234 azure blob storage service
  Streetcode/Streetcode.BLL/Interfaces/BlobStorage/IBlobService.cs
  Streetcode/Streetcode.BLL/Services/BlobStorageService/AzureBlobService.cs
  Streetcode/Streetcode.BLL/Services/BlobStorageService/BlobEnvirovmentVariables.cs
  Streetcode/Streetcode.BLL/Services/BlobStorageService/BlobService.cs
  Streetcode/Streetcode.BLL/Services/BlobStorageService/BlobServiceBase.cs
  Streetcode/Streetcode.BLL/Streetcode.BLL.csproj
  Streetcode/Streetcode.WebApi/Extensions/SeedingLocalExtension.cs
  Streetcode/Streetcode.WebApi/Extensions/ServiceCollectionExtensions.cs
  Streetcode/Streetcode.WebApi/Program.cs
Labels: feature

#269 F/add user deletion
  Streetcode/Streetcode.BLL/DTO/Users/DeleteUserResponseDto.cs
  Streetcode/Streetcode.BLL/Interfaces/Users/ITokenService.cs
  Streetcode/Streetcode.BLL/Mapping/Users/UserProfile.cs
  Streetcode/Streetcode.BLL/MediatR/Account/Delete/DeleteUserCommand.cs
  Streetcode/Streetcode.BLL/MediatR/Account/Delete/DeleteUserCommandHandler.cs
  Streetcode/Streetcode.BLL/MediatR/Account/Login/LoginUserHandler.cs
  Streetcode/Streetcode.BLL/MediatR/Account/Logout/LogoutUserHandler.cs
  Streetcode/Streetcode.BLL/MediatR/Account/RefreshToken/RefreshTokenHandler.cs
  Streetcode/Streetcode.BLL/MediatR/Account/Register/RegisterUserHandler.cs
  Streetcode/Streetcode.BLL/Resources/ErrorMessages.Designer.cs
  Streetcode/Streetcode.BLL/Resources/ErrorMessages.resx
  Streetcode/Streetcode.BLL/Services/CookieService/Interfaces/ICookieService.cs
  Streetcode/Streetcode.BLL/Services/CookieService/Realizations/CookieService.cs
  Streetcode/Streetcode.BLL/Services/Tokens/TokenService.cs
  Streetcode/Streetcode.WebApi/Controllers/Account/AccountController.cs
  Streetcode/Streetcode.WebApi/Extensions/ServiceCollectionExtensions.cs
  Streetcode/Streetcode.XUnitTest/MappingTests/User/UserProfileTests.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/Account/Delete/DeleteUserHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/Account/Login/LoginUserHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/Account/Logout/LogoutUserTests.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/Account/RefreshToken/RefreshTokenTests.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/Account/Register/RegisterUserHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/Services/CookieService/CookieServiceTests.cs
Labels: feature

#274 235 Fix flaky tests
  Streetcode/Streetcode.BLL/MediatR/Media/Art/Delete/DeleteArtHandler.cs
  Streetcode/Streetcode.BLL/MediatR/Sources/SourceLinkCategory/DeleteContentCategory/DeleteContentCategoryHandler.cs
  Streetcode/Streetcode.BLL/MediatR/Streetcode/Fact/GetByStreetcodeId/GetFactByStreetcodeIdHandler.cs
  Streetcode/Streetcode.BLL/MediatR/Team/GetById/GetByIdTeamHandler.cs
  Streetcode/Streetcode.BLL/MediatR/Timeline/TimelineItem/Update/UpdateTimelineItemHandler.cs
  Streetcode/Streetcode.BLL/Resources/MessageResourceContext.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/Account/Login/LoginUserHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/Account/Logout/LogoutUserTests.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/Account/RefreshToken/RefreshTokenTests.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/Media/Art/DeleteArtHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/Sources/DeleteContentCategoryHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/Sources/GetCategoriesByStreetcodeIdHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/Streetcode/Facts/CreateFactHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/Streetcode/Facts/GetAllFactsHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/Streetcode/Facts/GetFactByIdHandlerTest.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/Streetcode/Facts/GetFactByStreetcodeIdHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/Streetcode/Facts/ReorderFactsHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/Streetcode/RelatedTerm/DeleteRelatedTermByIdHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/Streetcode/RelatedTerm/GetRelatedTermByIdHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/Streetcode/Streetcode/CreateStreetcodeHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/Streetcode/Term/DeleteTermByIdHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/Streetcode/Text/UpdateTextHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/Team/GetAllTeamHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/Team/GetByIdTeamTests.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/TimelineItem/UpdateTimelineHandlerTests.cs
Labels: refactoring, unit-test

#282 Fixed bugs in refreshToke and delete UserHandler
  Streetcode/Streetcode.BLL/MediatR/Account/Delete/DeleteUserCommand.cs
  Streetcode/Streetcode.BLL/MediatR/Account/RefreshToken/RefreshTokenHandler.cs
  Streetcode/Streetcode.BLL/MediatR/Account/Register/RegisterUserHandler.cs
Labels: bug

#319 293 update get related figures by streetcodeId
  Streetcode/Streetcode.BLL/DTO/Streetcode/RelatedFigure/RelatedFigureDTO.cs
  Streetcode/Streetcode.BLL/Mapping/Streetcode/RelatedFigureProfile.cs
  Streetcode/Streetcode.BLL/MediatR/Streetcode/RelatedFigure/GetByStreetcodeId/GetRelatedFiguresByStreetcodeIdHandler.cs
  Streetcode/Streetcode.DAL/Entities/Streetcode/Types/EventStreetCode.cs
  Streetcode/Streetcode.WebApi/Extensions/SeedingLocalExtension.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/Streetcode/RelatedFigure/GetByStreetcodeId/GetRelatedFiguresByStreetcodeIdHandlerTests.cs
Labels: user story, feature

#325 253 google auth
  Streetcode/Streetcode.BLL/DTO/Users/LoginWithGoogleDTO.cs
  Streetcode/Streetcode.BLL/DTO/Users/UserDTO.cs
  Streetcode/Streetcode.BLL/MediatR/Account/LoginWithGoogle/LoginWithGoogleCommand.cs
  Streetcode/Streetcode.BLL/MediatR/Account/LoginWithGoogle/LoginWithGoogleHandler.cs
  Streetcode/Streetcode.BLL/MediatR/Account/LoginWithGoogle/LoginWithGoogleRequestDTOValidator.cs
  Streetcode/Streetcode.BLL/Services/Tokens/TokensConfiguration.cs
  Streetcode/Streetcode.BLL/Streetcode.BLL.csproj
  Streetcode/Streetcode.DAL/Streetcode.DAL.csproj
  Streetcode/Streetcode.WebApi/Controllers/Account/AccountController.cs
  Streetcode/Streetcode.WebApi/Streetcode.WebApi.csproj
  Streetcode/Streetcode.WebApi/libman.json
  Streetcode/Streetcode.XIntegrationTest/Streetcode.XIntegrationTest.csproj
  Streetcode/Streetcode.XUnitTest/MediatRTests/Account/Login/LoginUserHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/Account/LoginWithGoogle/LoginWithGoogleHandlerTests.cs
Labels: user story, investigate, feature

#316 UT fix converting to DateTimeOffset
  Streetcode/Streetcode.BLL/Converters/DateTimeToDateTimeOffsetConverter.cs
  Streetcode/Streetcode.BLL/MediatR/Account/RefreshToken/RefreshTokenHandler.cs
  Streetcode/Streetcode.BLL/MediatR/Account/Register/RegisterUserHandler.cs
  Streetcode/Streetcode.BLL/MediatR/Newss/GetById/GetNewsByIdHandler.cs
  Streetcode/Streetcode.BLL/MediatR/Newss/SortedByDateTime/SortedByDateTimeHandler.cs
  Streetcode/Streetcode.WebApi/Extensions/ServiceCollectionExtensions.cs
  Streetcode/Streetcode.WebApi/Properties/launchSettings.json
  Streetcode/Streetcode.XUnitTest/MediatRTests/Account/RefreshToken/RefreshTokenTests.cs
  Streetcode/Streetcode.XUnitTest/MediatRTests/Account/Register/RegisterUserHandlerTests.cs
  Streetcode/Streetcode.XUnitTest/Services/CookieService/CookieServiceTests.cs
Labels: bug, enhancement

#331 Blob fixed
  Streetcode/Streetcode.WebApi/Extensions/ServiceCollectionExtensions.cs
  Streetcode/Streetcode.WebApi/Properties/launchSettings.json
Labels: bug
